---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: simplewebapp
  namespace: test
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:production-*
spec:
  releaseName: simplewebapp
  chart:
#     git: ssh://git@github.com/pcherednichenko/kubernetesconf
    git: git@github.com/olgaglav/kubernetesconf
    ref: master
    path: charts/simplewebapp
  values:
    image:
      repository: gcr.io/aggregator-379711/github.com/olgaglav/modsen_intership_configserver
      tag: "production-8769acb6960fafab8f03d5106b54f5a60fada512"
    replicaCount: 1
    service:
      port: 80
    resources:
      requests:
        cpu: "200m"
        memory: "20Mi"
      limits:
        cpu: "400m"
        memory: "64Mi"

